on any move:
	if player is "ByNeoX_":
		if player's gamemode is survival:
			if block under the player is air:
				if {ee.%player%} is not set:
					wait 2 ticks
					if player is on ground:
						delete {ee.%player%}
						stop
					push the player upwards at speed 0.05
					push the player horizontally forwards at speed 0.02


on packet:
	if event-string is "PacketPlayInUseEntity":
		wait 3 ticks
		if targeted entity is a player:
			stop
		if distance between {stats} and event-entity is greater than 2.5:
			stop
		open "HOPPER" named "[Statistiques] » MLG" to player
		wait 2 ticks
		set slot 2 of player's current inventory to water bucket named "&9MLG" with lore "&8Type: Statistiques||||&7• &fPartie(s) Jouée(s): &e0||||&7• &fSaut(s) posé(s): &e0||&7• &fLuckyblock(s) récupéré: &e0||||&7• &fVictoire(s): &e0||&7• &fDéfaite(s): &e0"
		stop
on inventory click:
	if inventory name of player's current inventory is "[Statistiques] » MLG":
		cancel event

on join:
	set player's walk speed to 0.15


on damage:
	cancel event


command /addblock2:
	trigger:
		add location of targeted block to {blocks2::*}

command /resetblock2:
	trigger:
		delete {blocks2::*}


on quit:
	if number of all players = 1:
		set {anim} to false
		delete {s}
		delete {s2}
		delete {s3}
		loop all entities in radius 5 of {armor2}:
			if loop-entity is an armor stand:
				kill loop-entity

on join:
	wait 2 ticks
	if {s} is alive:
		stop
	else:
		wait 2 ticks
		if {sdf} is set:
			stop
		set {sdf} to true
		loop all entities in radius 5 of {armor2}:
			if loop-entity is an armor stand:
				kill loop-entity
		delete {s}
		delete {s1}
		delete {s3}
		wait 1 ticks
		spawn an armor stand at {armor1}
		set {s} to last spawned armor stand
		spawn an armor stand at {armor2}
		set helmet of {s} to player head with custom nbt "{display:{Name:""Piston""},SkullOwner:{Id:""949becc0-a56d-4a3b-a91c-7cd931923c83"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjQ0Yzk3OTgzY2E4YWFmNThjNjk2MTgyOTExZTNiYzY4NTEwZjI5ZDk2MzJkMTM0ZjgzNDU3YTUyZjRlNWY5NSJ9fX0=""}]}}}"
		add "{CustomName:""&aMap ##2 &7: &e&lMédieval"",CustomNameVisible:1b}" to nbt of {s}
		set {s2} to last spawned armor stand
		set helmet of {s2} to player head with custom nbt "{display:{Name:""Candy Cane (red)""},SkullOwner:{Id:""32cc3adf-2e6c-375e-3aef-9d62d391b587"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmIyMTYxN2QyNzU1YmMyMGY4ZjdlMzg4ZjQ5ZTQ4NTgyNzQ1ZmVjMTZiYjE0Yzc3NmY3MTE4Zjk4YzU1ZTgifX19""}]}}}"
		add "{CustomName:""&aMap ##1 &7: &c&lCan&f&ldy"",CustomNameVisible:1b}" to nbt of {s2}
		spawn an armor stand at {armor3}
		set {s3} to last spawned armor stand
		set helmet of {s3} to player head with custom nbt "{display:{Name:""Fire Orb""},SkullOwner:{Id:""1e2d1708-f4df-4eaa-8e94-e6345456347e"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzM2ODdlMjVjNjMyYmNlOGFhNjFlMGQ2NGMyNGU2OTRjM2VlYTYyOWVhOTQ0ZjRjZjMwZGNmYjRmYmNlMDcxIn19fQ==""}]}}}"
		add "{CustomName:""&aMap ##3 &7: &6&lWestern"",CustomNameVisible:1b}" to nbt of {s3}
		add "{NoBasePlate:1b,NoGravity:1b,Invisible:1b,DisabledSlots:2039583}" to nbt of {s}
		add "{NoBasePlate:1b,NoGravity:1b,Invisible:1b,ShowArms:1b,DisabledSlots:2039583}" to nbt of {s2}
		add "{NoBasePlate:1b,NoGravity:1b,Invisible:1b,ShowArms:1b,DisabledSlots:2039583}" to nbt of {s3}
		wait 0.4 seconds
		wait 3 ticks
		delete {sdf}
		while {s} is alive:
			wait 2 ticks
			add 8 to {_n}
			if {_n} is greater than 359:
				set {_n} to 8
			add "{Rotation:[%{_n}%f,0f]}" to nbt of {s}
			add "{Rotation:[%{_n}%f,0f]}" to nbt of {s2}
			add "{Rotation:[%{_n}%f,0f]}" to nbt of {s3}
		stop

command /animstop:
	trigger:
		set {anim} to false
		delete {s}
		delete {s2}
		delete {s3}
		loop all entities in radius 5 of {armor2}:
			if loop-entity is an armor stand:
				kill loop-entity		

command /Setanim <text>:
	trigger:
		set {armor%arg 1%} to location of player

command /f:
	trigger:
		add location of player to {part::*}
		set {part} to location of targeted block

command /h:
	trigger:
		delete {part::*}

every 1 seconds:
	wait 2 ticks
	loop {part::*}:
		set {_d} to loop-value
		add 0.5 to x-coordinate of {_d}
		loop all players:
			show 5 "DRIP_WATER" particles at {_d} for loop-player offset by 0.0, 0, 0
		delete {_d}